### ISSUE TITLE
Alert Groups to PSGallery?

### ISSUE THREAD

**Issue by AmarettoSlim** [awickham10/psdpa#20]
Hi @awickham10 ,

Two things, 

1. This module looks great, and as a former DBA automating interactions with DPA is awesome so thank you!

2. I saw this commit you just made, do you have any plans to publish it to PSGallery? 
 
https://github.com/awickham10/psdpa/commit/07d600e528fc1482e979d0cb5a036af377d09d61

Thanks for your time!

**Comment by awickham10** [comment]
Hey! I'm glad you're interested! The version of DPA that supports this hasn't been released yet. Once it comes out of release candidate state I plan on publishing to the gallery.

I'm also hoping they add some version information into their API so I can gracefully inform the user that their DPA version doesn't support some of these functions.

**Comment by AmarettoSlim** [comment]
Ah, got it. I'll have to go see when their next version is out of RC and wait patiently :) 

I agree it would be great if they added version metadata, I'll see if anyone has thrown that on THWACK.

I'll close this out, thanks for the insight!
